### ISSUE TITLE
FluxSink<FileHolder> sink value is always null , which returns NullPointerException on every run

### ISSUE THREAD

**Issue by ishivesh** [alexvuta/reactive-ftp-pooling-s3#1]
the sink property inside FileFlux class is null which results in NPE.

**Comment by ishivesh** [comment]
```
  @Override
  public FileHolder onNewItem(FileHolder item) {
    sink.next(item); <-- NPE

    return item;
  }
```


StackTrace

2020-02-21 16:58:01.357  INFO 17522 --- [pool-2-thread-1] c.v.r.f.aws.ftp.FtpPoolingScheduler      : name: 2000.zip date: Wed Nov 27 16:00:00 CET 2019 milis: 1574866800000 
java.lang.NullPointerException
	at com.vuta.reactive.filepooling.aws.service.FileFlux.onNewItem(FileFlux.java:24)
	at com.vuta.reactive.filepooling.aws.ftp.FtpPoolingScheduler.poolFTP(FtpPoolingScheduler.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

**Comment by ishivesh** [comment]
worked after fixing spring annotations
